apiKey: xxxxxx
rootUrl: https://opendata.government.bg
configs:
    - title: test-xls
      sourceType: XLS
      path: /tmp/source.xls
      days: 2
      resourceKey: 383ab793-5cc6-4eb8-8ceb-b2610921dc6e
      append: false
      pushAfterConfigChange: false